services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-shit
    ports:
      - "9000:9000"
      - "8123:8123"
    # volumes:
    #   - ./clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=shit
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
    restart: unless-stopped
  gin-web:
    build: .
    container_name: gin-web
    ports:
      - "8080:8080"
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse-shit
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
      - CLICKHOUSE_DB=shit
    restart: on-failure:3